from pathlib import Path
from typing import List, Tuple

CANONICAL_MASTER_SCHEMA: Tuple[str, ...] = (
    "Artist",
    "Artist_ID",
    "Contact_Name",
    "Contact_Role",
    "Contact_Type",
    "Organization",
    "Organization_Type",
    "Location",
    "City",
    "State",
    "Country",
    "Primary_Genre",
    "Secondary_Genre",
    "Song_Title",
    "Release_Date",
    "Career_Stage",
    "Primary_Email",
    "All_Emails",
    "Phone",
    "Website",
    "Domain",
    "Domain_Root",
    "Contact_Page_URL",
    "Facebook_URL",
    "Instagram_URL",
    "Instagram_Handle",
    "Twitter_URL",
    "SoundCloud_URL",
    "Bandcamp_URL",
    "Spotify_URL",
    "Spotify_Artist_ID",
    "LastFM_URL",
    "YouTube_URL",
    "TikTok_URL",
    "External_Links",
    "Played_On_Triple_J",
    "Played_On_Community_Radio",
    "Played_On_Unearthed",
    "Unearthed_Status",
    "Industry_Signals",
    "Source_Directory",
    "Discovery_Source",
    "Source_URL",
    "Import_Source_File",
    "Import_Batch",
    "Source_Job",
    "Date_Added",
    "First_Discovered_Date",
    "Last_Updated",
    "Last_Enriched",
    "Enrichment_Status",
    "Email_Source",
    "Email_Source_URL",
    "Email_Source_Type",
    "Email_Extract_Method",
    "Contact_Mode",
    "Domain_Type",
    "Domain_Organization",
    "Domain_Role",
    "Confidence",
    "Lead_Score",
    "Needs_Review",
    "Review_Reason",
    "Review_Urls",
    "Suspect_Email",
    "Suspect_Email_All",
    "Data_Quality_Score",
    "Lead_Status",
    "Outreach_Status",
    "Last_Contacted",
    "Followup_Count",
    "Final_Status",
    "Notes",
)


def get_canonical_master_schema() -> List[str]:
    return list(CANONICAL_MASTER_SCHEMA)


def get_default_master_csv_path() -> Path:
    repo_root = Path(__file__).resolve().parent.parent
    return repo_root / "data" / "master_lead_machine_contacts.csv"
