"""Additive Lead Engine V1 contract foundation.

This package is intentionally not imported by the live Lead Machine runtime.
"""

from .adapters import lead_record_from_row, source_occurrence_from_row
from .contracts import Evidence, LeadRecord, SourceOccurrence
from .identity import InsufficientIdentityEvidence
from .identity_evidence import (
    IdentityProfile,
    IdentitySignal,
    identity_profile_from_contracts,
    identity_profile_from_row,
)
from .export_ledger import (
    CampaignExport,
    CampaignExportLedger,
    CampaignExportRow,
    ExportField,
    ExportLineage,
    ExportedContactDestination,
    build_campaign_export,
    export_id,
    export_row_id,
)
from .registry import (
    HumanDecisionType,
    HumanIdentityDecision,
    IdentityAssertion,
    IdentityClassification,
    IdentityEvidenceRegistry,
    assertion_id,
    compare_identity_profiles,
    compare_identity_rows,
)
from .outreach_attribution import (
    AttributionClassification,
    AttributionEvidence,
    EngagedLeadHandoff,
    GmailDirection,
    GmailMessageRef,
    GmailThreadRef,
    OutreachAttempt,
    OutreachAttribution,
    OutreachAttributionRegistry,
    ReplyObservation,
    engaged_lead_handoff,
    evaluate_outreach_attribution,
    explicit_mapping_evidence,
    export_timestamp_evidence,
    gmail_message_ref,
    gmail_thread_ref,
    matching_evidence,
    observe_reply,
    outreach_attempt_from_export_row,
    outreach_attempt_id,
    privacy_fingerprint,
    recipient_evidence,
)

__all__ = [
    "Evidence",
    "CampaignExport",
    "CampaignExportLedger",
    "CampaignExportRow",
    "ExportField",
    "ExportLineage",
    "ExportedContactDestination",
    "InsufficientIdentityEvidence",
    "HumanDecisionType",
    "HumanIdentityDecision",
    "IdentityAssertion",
    "IdentityClassification",
    "IdentityEvidenceRegistry",
    "IdentityProfile",
    "IdentitySignal",
    "AttributionClassification",
    "AttributionEvidence",
    "EngagedLeadHandoff",
    "GmailDirection",
    "GmailMessageRef",
    "GmailThreadRef",
    "LeadRecord",
    "OutreachAttempt",
    "OutreachAttribution",
    "OutreachAttributionRegistry",
    "ReplyObservation",
    "SourceOccurrence",
    "lead_record_from_row",
    "assertion_id",
    "compare_identity_profiles",
    "compare_identity_rows",
    "build_campaign_export",
    "export_id",
    "export_row_id",
    "identity_profile_from_row",
    "identity_profile_from_contracts",
    "source_occurrence_from_row",
    "engaged_lead_handoff",
    "evaluate_outreach_attribution",
    "explicit_mapping_evidence",
    "export_timestamp_evidence",
    "gmail_message_ref",
    "gmail_thread_ref",
    "matching_evidence",
    "observe_reply",
    "outreach_attempt_from_export_row",
    "outreach_attempt_id",
    "privacy_fingerprint",
    "recipient_evidence",
]
